= Build Windup from Source

This information is provided for developers who plan to contribute code
to the Windup open source project. 

It is assumed that you have downloaded the Windup source code as described here: link:./Dev:-Get-the-Windup-Source-Code[Get the Windup Source Code]


== System Requirements to Build Windup

1.  Java 1.7.
+
You can choose from the following:
+
--------------
OpenJDK
Oracle Java SE
--------------
2.  Maven 3.1.1 or newer
+
If you have not yet installed or configured Maven, see
link:./Install-and-Configure-Maven[Install and Configure Maven] for details.
+
If you have installed Maven, you can check the version by typing the
following in a command prompt:
+
--------------
mvn --version 
--------------
3.  IDE requirements
+
If you prefer, you can work within an IDE. The following IDEs are recommended.

* http://www.jboss.org/products/devstudio/download/[Red Hat JBoss
Developer Studio 7.1.1] or newer
* https://www.eclipse.org/downloads/[Eclipse 4.3 (Kepler)] or newer

+
You must also make sure the IDE embeds Maven 3.1.1 or later. See
link:./Install-and-Configure-Maven[Install and Configure Maven] for details.


== Build Windup Using Maven Command Line


1.  Make sure you have configured Maven as described here:
link:./Install-and-Configure-Maven[Install and Configure Maven].
2. Check out Windup source code: `git co git@github.com:windup/windup.git Windup`
2. Open a command terminal and navigate to the root of the Windup project directory.
+
--------------
    cd Windup/
--------------
3.  To create a branch and build Windup using the latest version of the source code:

*  Fetch the latest source code from the upstream repository.
+ 
---------
git fetch upstream 
---------
*  Checkout a local copy of the branch.
+
-----------------------------------------------
git checkout -b BRANCH_NAME upstream/master
-----------------------------------------------

4.  Build the project.
+
-----------------
mvn clean install
-----------------

+
You can also build the project without the tests.
+
---------------------------------
mvn clean install -DskipTests
---------------------------------

== Build Windup Using Red Hat JBoss Developer Studio or Eclipse

1.  Make sure you have configured the Maven installation in your IDE as
described here:
https://github.com/windup/windup/wiki/Install-and-Configure-Maven[Install
and Configure Maven].
2.  Start JBoss Developer Studio or Eclipse.
3.  From the menu, select `File` → `Import`.
4.  In the selection list, choose `Maven` → `Existing Maven Projects`,
then click Next.
5.  Click `Browse` and navigate to the root of the Windup
project directory, then click `OK`.
6.  After all projects are listed, click `Next`. Ignore any Maven build
or dependency errors and click `Finish`. If you get a dialog titled
_Incomplete Maven Goal Execution_, ignore it and click `OK` to continue.
7.  In the Project Explorer tab, find the `windup_parent` project in the
list, right-mouse, and choose `Run As` --> `Maven install`.