[[install-windup-into-forge]]
Install Windup into Forge
~~~~~~~~~~~~~~~~~~~~~~~~~

1.  Download and install the latest version of
http://forge.jboss.org/[Forge 2] for your OS. This is currently Forge
2.8.1.Final.
2.  link:./Dev:-Build-Windup-from-Source[Build Windup from Source]
3.  Install the Windup UI Addon and Rules addons:
+
---------------------------------------------------------------------------
forge -b --install org.jboss.windup:ui,2.0.0-SNAPSHOT
forge -b --install org.jboss.windup.rules.apps:rules-java,2.0.0-SNAPSHOT
forge -b --install org.jboss.windup.rules.apps:rules-java-ee,2.0.0-SNAPSHOT
---------------------------------------------------------------------------
+
____________________________________
Installation completed successfully.
____________________________________

[[run-windup]]
Run Windup
~~~~~~~~~~

[[interactive-run]]
Interactive run
^^^^^^^^^^^^^^^

1.  Start Forge 2:

`forge`

1.  Run Windup:

`[Desktop]$ windup-migrate-app --input /path/to/jee-example-app-1.0.0.ear --output /path/to/jee-example-app-1.0.0.ear.report --packages org.example.* com.example.*`

____________________________________________
`***SUCCESS*** Windup execution successful!`
____________________________________________

1.  View the report in the directory specified on the command line:
_/path/to/jee-example-app-1.0.0.ear.report_

[[batch-run-for-a-shell-script]]
Batch run (for a shell script)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1.  Run
`forge --evaluate "windup-migrate-app --input ... --output ... --packages com.foo org.foo"`
Run `forge` and then `man windup-migrate-app` to see the possible
parameters.