= Execute Windup

_For the impatient: (detailed steps below)_
------------------
wget -O forge.zip https://repository.jboss.org/nexus/service/local/repositories/releases/content/org/jboss/forge/forge-distribution/2.10.1.Final/forge-distribution-2.10.1.Final-offline.zip
unzip forge.zip
mv forge-distribution-2.10.1.Final Forge

export FORGE_HOME=./Forge/
export PATH=$PATH:$FORGE_HOME/bin
forge -b --install org.jboss.windup:ui,2.0.0-SNAPSHOT
forge -b --install org.jboss.windup.rules.apps:rules-java,2.0.0-SNAPSHOT
forge -b --install org.jboss.windup.rules.apps:rules-java-ee,2.0.0-SNAPSHOT

forge
# windup-migrate-app --input /home/ondra/work/Migration/TestApps/_apps/BradApp --output Report --packages org com net
# Ctrl + D

firefox Report/index.html
------------------

== Install Windup into Forge

NOTE: If you installed the Windup add-ons into a previous version of Forge, delete the `${user.home}/.forge/addons/` directory. Otherwise you may see the following error when you execute Windup:  
           _Command: windup-migrate-app was not found_


1.  Download and install the latest version of
http://forge.jboss.org/[Forge 2] for your OS. This is currently Forge
2.8.1.Final. The steps to download, install, and configure the Forge distribution can be found here: http://forge.jboss.org/document/installation.
2.  link:./Dev:-Build-Windup-from-Source[Build Windup from Source]
3.  Install the Windup UI Addon and Rules addons using the following commands:
+
---------------------------------------------------------------------------
forge -b --install org.jboss.windup:ui,2.0.0-SNAPSHOT
forge -b --install org.jboss.windup.rules.apps:rules-java,2.0.0-SNAPSHOT
forge -b --install org.jboss.windup.rules.apps:rules-java-ee,2.0.0-SNAPSHOT
---------------------------------------------------------------------------
+
You should see the following message upon the completion of each of the above commands.
+
____________________________________
Installation completed successfully.
____________________________________

== Run Windup

You can run Windup interactively or in batch mode using the Forge `windup-migrate-app` command. 

=== Run Windup Interactively

1.  Start Forge 2:
+
-----
forge
-----
2.  Run Windup using the following syntax:
+
------------
windup-migrate-app --input INPUT_ARCHIVE_OR_FOLDER --output OUTPUT_REPORT_DIRECTORY --packages PACKAGE_1 PACKAGE_2 PACKAGE_N
------------
+
Where:

* `INPUT_ARCHIVE_OR_FOLDER` is the fully qualified application archive or source path
* `OUTPUT_REPORT_DIRECTORY` is the fully qualified path to the folder that will contain the the report information produced by Windup.
* `PACKAGE_1`, `PACKAGE_2`, `PACKAGE_N` are the packages to be evaluated by Windup.

3. You should see the following result upon completion of the command:
+
____________________________________________
***SUCCESS*** Windup execution successful!
____________________________________________
4.  Open the `OUTPUT_REPORT_DIRECTORY/index.html` file in a browser to access the report.
The following subdirectories in the `OUTPUT_REPORT_DIRECTORY` contain the supporting information for the report:
** archives/
** graph/
** renderedGraph/
** reports/
** stats/

+
For details on how to evaluate the report data, see link:Review-the-Report[Review the Report].
5. To see the list of available parameters for the `windup-migrate-app` command, type the following in the Forge prompt.
+
----
man windup-migrate-app
----

=== Run Windup Using a Provided Example Application

Windup source code provides a number of example applications `test-files/` directory to demonstrate the tool. To run Windup using the `spring-small-example.war` file, perform the following steps:

1. Navigate to the root directory of the Windup source.
2. Start Forge 2.
+
-----
forge
-----

3. Execute the following command:

+
----
$ windup-migrate-app --input test-files/spring-small-example.war --output output-reports/spring-small-example-war-report --packages spring.framework
----
4. This command generates the `output-reports/spring-small-example-war-report/` structure in the root directory of the Windup source. You can redirect the report to a different path by specifying a fully qualified path name.
5. Open the `output-reports/spring-small-example-war-report/index.html` file in a browser to access the report.

=== Run Windup in Batch Mode (for a shell script)

To run the Forge `windup-migrate-app` command in batch mode, use the following syntax:
----
forge --evaluate "windup-migrate-app --input INPUT_ARCHIVE --output OUTPUT_REPORT --packages PACKAGE_1 PACKAGE_2 PACKAGE_N"
----

