= Glossary of Terms Used in Windup

== Rules 

Rule:: A piece of code that performs a single unit of work during the migration process. Depending on the complexity of the rule, it may or may not include configuration data. Extensive configuration information may be externalized into external configuration, for example, a custom XML file. The following is an example of a Java-based rule added to the `JDKConfig` RuleProvider class.

[source,java]
----
.addRule()
    .when(JavaClass.references("java.lang.ClassLoader$").at(TypeReferenceLocation.TYPE))
    .perform(Classification.as("Java Classloader, must be migrated.")
    .with(Link.to("Red Hat Customer Portal: How to get resources via the ClassLoader in a JavaEE application in JBoss EAP",  "https://access.redhat.com/knowledge/solutions/239033"))
     .withEffort(1))
----

RuleProvider:: A class that implements one or more rules using the `.addRule()` method. The following are examples of legacy Java RulesProviders that are defined in `rules-java-ee` ruleset.

* EjbConfig
* JDKConfig
* SeamToCDI

Ruleset:: A Windup plug-in (Forge add-on) that targets a specific area of migration, for example, `Spring -> Java EE 6` or `WebLogic -> JBoss EAP`. It contains one or more RuleProviders along with additional information needed for the migration such as operations, conditions, report templates, static files, metadata, relationships to other rulesets. The following Windup projects are rulesets.

* rules-java-ee
* rules-xml

Rules Metadata:: Information about whether a particular ruleset applies to a given situation. The metadata can include the source and target platform and frameworks.

Rules Pipeline:: A collection of rules that feed information into the knowledge graph.

== Reporting

Lift and Shift (Level of effort):: The code or file is standards-based and can be ported to the new environment with no changes.

Mapped (Level of effort):: There is a standard mapping algorithm to port the code or file to the new environment.

Custom (Level of effort):: The code or file must be rewritten or modified to work in the new environment.

