[[welcome-to-windup-2.0]]
Welcome to Windup 2.0
---------------------

_NOTE: The Windup 2.0 project is currently under development. If you
want to contribute or participate in developer discussions, join us on
the irc.freenode.net #windup channel or subscribe to the windup-dev
mailing list at https://lists.jboss.org/mailman/listinfo/windup-dev._

[[about-windup]]
About Windup
^^^^^^^^^^^

Windup 2.0 is a tool used to simplify Java application migrations. It is the 
sequel to the original Windup 0.7.x, which has moved to the 
https://github.com/windup/windup-legacy[windup-legacy] GitHub repository.

* link:What-is-Windup[What is Windup]?
* link:Windup-Project-Information[Windup Project Information] - Github
repository, IRC, Mailing lists, ...
* link:Get-Involved[Get Involved] - We need your feedback!
* link:./Install-and-Configure-Maven[Install and Configure Maven]
* link:./Dev:-Get-the-Windup-Source-Code[Get the Windup Source Code]
* link:./Dev:-Build-Windup-from-Source[Build Windup from Source]
* link:./Execute-Windup[Execute Windup]
* link:Review-the-Report[Review the Report]
* link:./Glossary[Glossary of Terms]

[[windup-guides]]
Windup Guides
~~~~~~~~~~~~~

Windup documentation is organized into guides that target specific
audiences.

* link:./Dev:-Developer-Guide[Developer Guide]: 
This guide provides information for developers who plan to contribute 
source code updates or core rule add-ons to the Windup 2.0 project.
* link:./Rules:-Rules-Development-Guide[Rules Development Guide]: 
This guide provides details for developers, consultants, and others 
who plan to create custom rule add-ons for the Windup 2.0 project.
* link:./User:-User-Guide[User Guide]:
This guide is for engineers, consultants, or others who plan to use
Windup to migrate applications or other components.
* link:./Plan:-Migration-Planning-Guide[Migration Planning Guide]: 
This guide is for developers, Project Managers, or IT managers who must 
interpret the Windup reports and develop a project plan.
