= Windup Project Information

== Github Repository

The Windup project github repository is located at https://github.com/windup/windup/.

See the
link:./Dev:-Developer-Guide[Developer Guide] for details on how to 
link:./Dev:-Get-the-Windup-Source-Code[Get the Windup Source Code], how to
link:./Dev:-Build-Windup-from-Source[Build Windup from Source], and how to
link:./Dev:-Create-JavaDoc-for-Windup[Create JavaDoc for Windup].


== Documentation

The Windup documentation is currently located here in the Windup project link:./[Wiki].

For additional information, refer to the Javadoc. 

== Website

There is currently no website for Windup 2.0.

The windup.jboss.org website currently provides information primarily
for legacy Windup 1.x (legacy).

== IRC chat

Server: irc.freenode.net +
Channel: #windup

== Mailing lists

Subscribe to the JBoss mailing lists at
https://lists.jboss.org/mailman/listinfo/windup-dev.

* Core development discussion: windup-dev@redhat.com
* Rules development discussion, usage: windup-users@redhat.com

== Core development team (and IRC nicks)

Lead: Lincoln Baxter (lincolnthree) +
Members: Jess Sightler (jsightler), Matej Briskar (mbriskar), Ondrej
Zizka (ozizka)